[8.0] Add gs1 serial numbers on packages for logistics
OCA/stock-logistics-tracking pull request #13
Opened 2016-09-19 09:21 UTC by rousseldenis

2016-09-29 14:25 UTC, lmignon commented
@rousseldenis Can you add unittests PLZ?

2016-09-29 14:31 UTC, rousseldenis commented
@lmignon Ok, I'll do it, it should avoid fixing...

2016-09-30 05:52 UTC, lmignon requested changes

2016-09-30 05:52 UTC, lmignon commented on stock_packaging_serial/static/description/icon.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
PLZ remove this file

2016-09-30 05:52 UTC, lmignon commented on stock_packaging_serial_sscc/static/description/icon.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
plz remove this file

2016-09-30 07:15 UTC, rousseldenis commented
@lmignon Done!

2016-09-30 15:58 UTC, lmignon requested changes
Can you take a look to the pep8 error in travis?
https://travis-ci.org/OCA/stock-logistics-tracking/jobs/164057882#L430

2022-05-08 12:13 UTC, closed without merging