[13.0][IMP] stock_picking_manual_package: Allow select in wizard the product to put in pack
OCA/stock-logistics-tracking pull request #30
Opened 2022-06-20 21:27 UTC by sergio-teruel

cc @Tecnativa

ping @chienandalu @victoralmau

2022-06-21 07:13 UTC, rousseldenis commented on stock_picking_manual_package/wizards/stock_picking_manual_package_wiz.py
>  class StockPicking(models.TransientModel):
I'd suggest you to adapt this to model name

2022-06-21 07:13 UTC, rousseldenis commented on stock_picking_manual_package/wizards/stock_picking_manual_package_wizard_view.xml
> +                    <field name="picking_product_ids" invisible="1" />
I'd suggest you to enhance the <p> message in order to help easily user to deal with product_ids field (without hover).

2022-06-21 09:20 UTC, sergio-teruel commented
Thanks @rousseldenis Changes done.. but I change the title of this PR because I have an idea in my mind... 
Maybe I could add a One2many field in the wizard to specifi lines by products... but by the moment is an idea...

2022-06-21 15:46 UTC, victoralmau approved these changes
Code review OK.

2022-07-04 23:08 UTC, cesar-tecnativa requested changes

2022-07-04 23:08 UTC, cesar-tecnativa commented on stock_picking_manual_package/wizards/stock_picking_manual_package_wiz.py
> +    picking_product_ids = fields.Many2many(
If you add two many2many product_product, you have to define table names.

2023-04-03 06:32 UTC, pedrobaeza approved these changes
/ocabot merge minor

2023-04-03 07:10 UTC, chienandalu approved these changes

2023-04-03 08:03 UTC, merged